title: The Risky Pipeline
description: Musings on devops and risk management problems
author: Adam M. Lechnos
github: https://github.com/adam-lechnos
about: Devops engineer in the fintech space with a background in GRC & Risk Management consulting
disqus_shortname: risky-pipeline
google_analytics: UA-47832702-1

enableTags: true
tagarray: []

#collections:
#project:
#output: true
#permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "http://www.twitter.com/Adam_Lechnos"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/adamlechnos"
    - icon: fa-github
      link: "https://github.com/adam-lechnos"

share:
  twitter_username: adam_lechnos

urls:
    - text: About Me
      url: /about/
      #- text: My Projects
      #url: /projects/
    - text: Code Repos
      url: /repos
    - text: Published Work
      url: /published
    - text: Other Interests
      url: /other
    - text: XML Feed
      url: /feed.xml

url: "https://adamlechnos.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
